In [1]:
import numpy as np

In [ ]:
np.random.rand(9, 9)

In [ ]:
import random


class Genome:
    fitness = random.randint(1, 10)

In [ ]:
a = Genome
b = Genome

type(Genome()), type(Genome)

In [ ]:
np.arange(1, 3) @ np.arange(2, 4)

In [ ]:
a = np.random.rand(5)
for i in range(5):
    a[i] += 1
a

In [ ]:
import itertools


sum(1 for i in itertools.product([0, 1, -1], repeat=9))

In [ ]:
-np.random.rand(9).a

In [ ]:
abs(-np.random.rand(9))

In [ ]:
arr = np.random.rand(9)

In [ ]:
arr.count

In [ ]:
np.count_nonzero(arr)

In [ ]:
hash(arr.tobytes())

In [ ]:
(0,) * 9

In [1]:
from functools import cache
@cache
def a(x):
    if x == 0:
        return 0
    return x + a(x - 1) 

In [2]:
def b(g):
    return lambda x: g(x) + 0.5

In [3]:
f = b(a)

In [ ]:
f(7111)

: 

: 

In [ ]:
def make_exception():    
    try:
        1/1
    
    finally:
        return 'finally'

make_exception()  # 'finally'

In [2]:

winningCombination = np.array([
    [ 0, 1, 2 ],
    [ 3, 4, 5 ],
    [ 6, 7, 8 ],
    [ 0, 3, 6 ],
    [ 1, 4, 7 ],
    [ 2, 5, 8 ],
    [ 0, 4, 8 ],
    [ 2, 4, 6 ],
    ])

In [3]:
board = np.array([ 0,  1,  0,
            1, -1, -1,
            0,  1, -1])

In [9]:
line_sums = board[winningCombination].sum(axis=1)
line_sums

array([ 1, -1,  0,  1,  1, -2, -2, -1])

In [15]:
bool(np.isin(-3, line_sums))

False

In [16]:
def f():
    for _ in range(10**6):
        pass

In [19]:
import timeit


timeit.timeit(f, number=1)

0.013329200000953279

In [26]:
arr = np.random.rand(1000_000_000)
arr

array([0.92142161, 0.79781391, 0.8904931 , ..., 0.50746237, 0.48833127,
       0.47954251])

In [28]:
for _ in range(1000):
    0.9 in arr

KeyboardInterrupt: 

In [42]:
0.9 in arr

False

In [43]:
any(i == 0.9 for i in arr)

KeyboardInterrupt: 

In [54]:
np.put(board, 3, -1)

In [55]:
board

array([ 0,  1,  0, -1, -1, -1,  0,  1, -1])

In [56]:
def put_copy(arr, ind, v,):
    arr_copy = arr.copy()
    np.put(arr_copy, ind, v)
    return arr_copy

In [57]:
put_copy(board, 0, 10)

array([10,  1,  0, -1, -1, -1,  0,  1, -1])

In [60]:
np.arange(9)[board == 0].max(key=)

array([0, 2, 6])

In [61]:
import math


def f(x):
    return math.log(x)

In [62]:
f(np.arange(1, 2))

TypeError: only size-1 arrays can be converted to Python scalars